version: "3"

services:

mysql:
image: mysql:8
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: povos_indigenas
ports:
- "3306:3306"

api:
build: .
ports:
- "8080:8080"
depends_on:
- mysql